### ISSUE TITLE
滑动验证码

### ISSUE THREAD

**Issue by czp3009** [Dawnnnnnn/bilibili-captcha#1]
楼主能训练一个滑动验证码的轨迹数据集么.

B站现在的 oauth v3 接口在多次登录失败之后, 跳出来的是滑动验证(极验).

APP 上它不会收集滑动前的鼠标位置数据, 因为没有任何点击, 只需要轨迹即可.

接口是这样的

https://passport.bilibili.com/api/v3/oauth2/login

多次失败之后会返回这样的东西

{"ts":1550569982,"code":-105,"data":{"url":"https://passport.bilibili.com/register/verification.html?success=1&gt=b6e5b7fad7ecd37f465838689732e788&challenge=9a67afa4d42ede71a93aeaaa54a4b6fe&ct=1&hash=105af2e7cc6ea829c4a95205f2371dc5"},"message":"验证码错误!"}

这个里面的 url 用 WebView 打开就是一个极验.

求求楼主, 救救我

**Comment by Dawnnnnnn** [comment]
有基于webdriver的模拟轨迹，调参成功率挺高的，你可以自己训练下？QQ见

**Comment by czp3009** [comment]
见个鸡巴, 不见不散
